# Generated by Django 5.0 on 2023-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habrie', '0002_alter_student_address_alter_student_contact_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
